// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/ssm_client/ssm_client.go

// Package mock_ssm_client is a generated GoMock package.
package mock_ssm_client

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSsmClientInterface is a mock of SsmClientInterface interface.
type MockSsmClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSsmClientInterfaceMockRecorder
}

// MockSsmClientInterfaceMockRecorder is the mock recorder for MockSsmClientInterface.
type MockSsmClientInterfaceMockRecorder struct {
	mock *MockSsmClientInterface
}

// NewMockSsmClientInterface creates a new mock instance.
func NewMockSsmClientInterface(ctrl *gomock.Controller) *MockSsmClientInterface {
	mock := &MockSsmClientInterface{ctrl: ctrl}
	mock.recorder = &MockSsmClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSsmClientInterface) EXPECT() *MockSsmClientInterfaceMockRecorder {
	return m.recorder
}

// GetValue mocks base method.
func (m *MockSsmClientInterface) GetValue(name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValue", name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValue indicates an expected call of GetValue.
func (mr *MockSsmClientInterfaceMockRecorder) GetValue(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValue", reflect.TypeOf((*MockSsmClientInterface)(nil).GetValue), name)
}

// Search mocks base method.
func (m *MockSsmClientInterface) Search(name string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", name)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockSsmClientInterfaceMockRecorder) Search(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSsmClientInterface)(nil).Search), name)
}
