// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/rds_client/rds_client.go

// Package mock_rds_client is a generated GoMock package.
package mock_rds_client

import (
	reflect "reflect"

	types "github.com/aws/aws-sdk-go-v2/service/rds/types"
	gomock "github.com/golang/mock/gomock"
)

// MockRdsClientInterface is a mock of RdsClientInterface interface.
type MockRdsClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRdsClientInterfaceMockRecorder
}

// MockRdsClientInterfaceMockRecorder is the mock recorder for MockRdsClientInterface.
type MockRdsClientInterfaceMockRecorder struct {
	mock *MockRdsClientInterface
}

// NewMockRdsClientInterface creates a new mock instance.
func NewMockRdsClientInterface(ctrl *gomock.Controller) *MockRdsClientInterface {
	mock := &MockRdsClientInterface{ctrl: ctrl}
	mock.recorder = &MockRdsClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRdsClientInterface) EXPECT() *MockRdsClientInterfaceMockRecorder {
	return m.recorder
}

// GetAllDBClusters mocks base method.
func (m *MockRdsClientInterface) GetAllDBClusters() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllDBClusters")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetAllDBClusters indicates an expected call of GetAllDBClusters.
func (mr *MockRdsClientInterfaceMockRecorder) GetAllDBClusters() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllDBClusters", reflect.TypeOf((*MockRdsClientInterface)(nil).GetAllDBClusters))
}

// GetAllDBInstances mocks base method.
func (m *MockRdsClientInterface) GetAllDBInstances() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllDBInstances")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetAllDBInstances indicates an expected call of GetAllDBInstances.
func (mr *MockRdsClientInterfaceMockRecorder) GetAllDBInstances() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllDBInstances", reflect.TypeOf((*MockRdsClientInterface)(nil).GetAllDBInstances))
}

// GetDBCluster mocks base method.
func (m *MockRdsClientInterface) GetDBCluster(identifier string) (*types.DBCluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDBCluster", identifier)
	ret0, _ := ret[0].(*types.DBCluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDBCluster indicates an expected call of GetDBCluster.
func (mr *MockRdsClientInterfaceMockRecorder) GetDBCluster(identifier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDBCluster", reflect.TypeOf((*MockRdsClientInterface)(nil).GetDBCluster), identifier)
}

// GetDBInstance mocks base method.
func (m *MockRdsClientInterface) GetDBInstance(identifier string) (*types.DBInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDBInstance", identifier)
	ret0, _ := ret[0].(*types.DBInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDBInstance indicates an expected call of GetDBInstance.
func (mr *MockRdsClientInterfaceMockRecorder) GetDBInstance(identifier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDBInstance", reflect.TypeOf((*MockRdsClientInterface)(nil).GetDBInstance), identifier)
}
